# SOPS configuration for ABA secrets
# Keys listed here can decrypt secrets in this repo.
keys:
  - &local age1lgs9xekgvhr64l3tv8jtka72nmng7x0gk555d327pgd3dgyz74ssehnz9x
  - &server age1ycwttm5dx9yp2q8xsw8cy5un6kl9zqf0wl4afgdrxku5nepflygq5emk0x
creation_rules:
  - path_regex: secrets/.*
    key_groups:
      - age:
          - *local
          - *server
