# NixOS configuration for the ABA agent VPS
#
# Deployed after nixos-infect converts a blank VPS to NixOS.
# This configuration implements the security model from specs/security.md:
#
#   1. The `aba` user runs the agent loop. It has NO access to API keys.
#   2. The `aba-proxy` system user owns the nginx process that holds API keys.
#   3. nginx on 127.0.0.1:8080 injects auth headers and forwards to real APIs.
#   4. SOPS + age decrypts keys at deploy time into files only root/aba-proxy can read.
#   5. The aba user talks to localhost:8080 -- never to api.anthropic.com directly.
#
# API keys are PLACEHOLDERS here. Real keys come from SOPS decryption at deploy time.
# See the sops-nix section and specs/security.md for the full flow.

{ config, pkgs, lib, ... }:

let
  # SOPS-decrypted secrets land here at deploy time (tmpfs, root-only).
  # A systemd service reads them and writes nginx-readable key config.
  secretsDir = "/run/secrets";

  # nginx include file with actual API keys. Generated by systemd at boot.
  # Permissions: root:aba-proxy 0640 -- nginx can read, aba user cannot.
  apiKeysConf = "/etc/nginx/api-keys.inc";
in
{
  imports = [
    ./hardware-configuration.nix
  ];

  system.stateVersion = "24.11";

  # Workaround for https://github.com/NixOS/nix/issues/8502
  services.logrotate.checkConfig = false;

  boot.tmp.cleanOnBoot = true;
  zramSwap.enable = true;
  networking.hostName = "aba-agent";

  # --------------------------------------------------------------------------
  # Nix settings
  # --------------------------------------------------------------------------
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    trusted-users = [ "root" ];
  };

  # JJ 0.23.0 on 24.11 has GHSA-794x-2rpg-rfgr. Permit until we overlay nixpkgs-unstable.
  nixpkgs.config.permittedInsecurePackages = [
    "jujutsu-0.23.0"
  ];

  # --------------------------------------------------------------------------
  # Users
  # --------------------------------------------------------------------------

  # Root: keep SSH key for initial setup. TODO: remove after Tailscale is configured.
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGD5q9Gpe1gTyRQZz8m5bVVNWQgrwoG5+kbPt6x7NNmc aba-vps-2026-03-16"
  ];

  # The agent user. Runs ABA, has a login shell, can SSH in.
  # CANNOT read API keys, proxy config with keys, or proxy process memory.
  users.users.aba = {
    isNormalUser = true;
    home = "/home/aba";
    shell = pkgs.bash;
    extraGroups = [ ];  # Intentionally no extra groups -- least privilege
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGD5q9Gpe1gTyRQZz8m5bVVNWQgrwoG5+kbPt6x7NNmc aba-vps-2026-03-16"
    ];
  };

  # The proxy user. Owns the nginx worker processes.
  # System user: no login shell, no SSH, no home directory.
  # nginx workers run as this user and can read the key config file.
  users.users.aba-proxy = {
    isSystemUser = true;
    group = "aba-proxy";
    # No shell, no SSH -- this user exists solely for file ownership and process isolation
  };
  users.groups.aba-proxy = { };

  # --------------------------------------------------------------------------
  # ABA user shell profile
  # --------------------------------------------------------------------------
  # Write a .bashrc for the aba user so SSH sessions get a welcome message
  # and convenient aliases. Using an activation script since NixOS doesn't
  # have a per-user profile option for normal users.
  system.activationScripts.aba-bashrc = lib.stringAfter [ "users" ] ''
    cat > /home/aba/.bashrc <<'BASHRC'
# ABA agent shell profile (managed by NixOS -- do not edit manually)

# Proxy is configured system-wide via environment.variables:
#   PROXY_BASE_URL=http://127.0.0.1:8080/openai
#   PROXY_PROVIDER=openai
#   RUST_LOG=info

alias aba-loop='/home/aba/repos/aba/loop.sh'
alias aba-build='/home/aba/repos/aba/loop.sh build'
alias aba-plan='/home/aba/repos/aba/loop.sh plan'
alias aba-status='curl -s http://127.0.0.1:8080/health'

echo "========================================"
echo "  ABA Agent VPS"
echo "  Proxy: $PROXY_BASE_URL"
echo "  Provider: $PROXY_PROVIDER"
echo "========================================"
echo ""
echo "Commands:"
echo "  aba-loop    -- start the Ralph loop (build mode)"
echo "  aba-build   -- start the Ralph loop (build mode)"
echo "  aba-plan    -- start the Ralph loop (plan mode)"
echo "  aba-status  -- check proxy health"
echo ""
BASHRC
    chown aba:users /home/aba/.bashrc
    chmod 644 /home/aba/.bashrc
  '';

  # Directory where ABA can write key requests (human-in-the-loop flow).
  # ABA can create files here; only root can modify/delete them after creation.
  systemd.tmpfiles.rules = [
    "d /var/lib/aba 0755 aba aba -"
    "d /var/lib/aba/key-requests 1733 aba aba -"
    # 1733 = sticky bit + owner write + group/other write but not read others' files
    # ABA can create requests; only root can review all of them

    # Runtime directory for the token manager -- holds the fresh OpenAI API key.
    # root:aba-proxy so nginx (running as aba-proxy) can read the token file.
    "d /run/aba-proxy 0750 root aba-proxy -"
  ];

  # --------------------------------------------------------------------------
  # SSH hardening
  # --------------------------------------------------------------------------
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "prohibit-password";  # TODO: set to "no" after Tailscale setup
      KbdInteractiveAuthentication = false;
      X11Forwarding = false;
      MaxAuthTries = 3;
      # Only the aba user can SSH in. The aba-proxy user has no shell.
      AllowUsers = [ "root" "aba" ];  # TODO: remove root after Tailscale setup
    };
    # Disable unused auth methods
    extraConfig = ''
      AuthenticationMethods publickey
    '';
  };

  # --------------------------------------------------------------------------
  # Tailscale -- private network access
  # --------------------------------------------------------------------------
  services.tailscale.enable = true;

  # --------------------------------------------------------------------------
  # Fail2ban -- brute-force protection
  # --------------------------------------------------------------------------
  services.fail2ban = {
    enable = true;
    maxretry = 3;
    bantime = "1h";
    # SSH jail is enabled by default when openssh is enabled
  };

  # --------------------------------------------------------------------------
  # Firewall
  # --------------------------------------------------------------------------
  networking.firewall = {
    enable = true;
    # SSH: public access (key-only, fail2ban protected)
    # Tailscale: UDP 41641 for WireGuard tunnel establishment
    # Everything else is blocked. Port 8080 is localhost-only (nginx).
    allowedTCPPorts = [ 22 ];
    allowedUDPPorts = [ 41641 ];
    # Tailscale manages its own interface rules via the tailscale0 interface
  };

  # --------------------------------------------------------------------------
  # System packages
  # --------------------------------------------------------------------------
  environment.systemPackages = with pkgs; [
    # Development tools for ABA
    git
    jujutsu        # jj -- target VCS backend (see specs/source-control.md)
    rustup         # Rust toolchain management
    gcc            # C compiler/linker required by cargo/rustc
    pkg-config     # Build dependency for openssl-sys
    openssl        # TLS library for HTTP clients
    openssl.dev    # Development headers for openssl-sys crate

    # Secret management
    sops
    age

    # Operations
    tmux           # Persistent sessions for long-running Ralph loops
    htop           # Process monitoring
    curl           # Health checks and debugging
    jq             # JSON processing for key request files

    # Editors (for human SSH sessions)
    vim
  ];

  # Build environment for Rust/cargo (openssl-sys needs pkg-config to find openssl)
  # Proxy config so ABA talks to the local nginx key-injection proxy, not directly to APIs.
  environment.variables = {
    PKG_CONFIG_PATH = "/run/current-system/sw/lib/pkgconfig";
    PROXY_BASE_URL  = "http://127.0.0.1:8080/openai";
    PROXY_PROVIDER  = "openai";
    RUST_LOG        = "info";
  };

  # --------------------------------------------------------------------------
  # SOPS-nix: secret decryption at deploy time
  # --------------------------------------------------------------------------
  #
  # This section requires sops-nix to be added as a flake input.
  # The server's age key must be provisioned to /var/lib/sops-nix/keys.txt
  # before the first deploy.
  #
  # To set up:
  #   1. On the server: age-keygen -o /var/lib/sops-nix/keys.txt
  #   2. Add the public key to .sops.yaml in the repo
  #   3. Re-encrypt secrets: sops updatekeys secrets/api-keys.yaml
  #   4. Deploy: nixos-rebuild switch
  #
  # Uncomment when sops-nix is wired into the flake:
  #
  # sops = {
  #   defaultSopsFile = ../secrets/api-keys.yaml;
  #   age.keyFile = "/var/lib/sops-nix/keys.txt";
  #
  #   secrets."anthropic_api_key" = {
  #     owner = "root";
  #     group = "root";
  #     mode = "0400";
  #   };
  #   secrets."openai_api_key" = {
  #     owner = "root";
  #     group = "root";
  #     mode = "0400";
  #   };
  # };

  # --------------------------------------------------------------------------
  # API key config generation
  # --------------------------------------------------------------------------
  #
  # This systemd service runs before nginx starts. It reads SOPS-decrypted
  # secrets and writes an nginx-includable config snippet with the real keys.
  # The output file is owned by root:aba-proxy with mode 0640, so nginx
  # workers (running as aba-proxy) can read it but the aba user cannot.
  #
  # Until SOPS is wired up, this writes placeholder values so nginx can start.
  #
  systemd.services.generate-api-keys-conf = {
    description = "Generate nginx API key config from SOPS secrets";
    wantedBy = [ "multi-user.target" ];
    before = [ "nginx.service" ];
    requiredBy = [ "nginx.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      # Run as root to read secrets and set file ownership
      User = "root";
      Group = "root";
    };
    script = ''
      # Read decrypted secrets if they exist, otherwise use placeholders.
      # In production, SOPS secrets will be at /run/secrets/<name>.
      ANTHROPIC_KEY="PLACEHOLDER_SOPS_NOT_YET_CONFIGURED"
      OPENAI_KEY="PLACEHOLDER_SOPS_NOT_YET_CONFIGURED"

      if [ -f "${secretsDir}/anthropic_api_key" ]; then
        ANTHROPIC_KEY=$(cat "${secretsDir}/anthropic_api_key")
      fi
      if [ -f "${secretsDir}/openai_api_key" ]; then
        OPENAI_KEY=$(cat "${secretsDir}/openai_api_key")
      fi

      # Write the nginx include file with real keys.
      # This file is the ONLY place decrypted keys exist on disk (besides /run/secrets).
      mkdir -p /etc/nginx
      cat > "${apiKeysConf}" <<NGINX_KEYS
      # AUTO-GENERATED by generate-api-keys-conf.service
      # Do NOT edit manually. Keys come from SOPS decryption.
      # This file is included by the API proxy server block.

      # Variables used in proxy_set_header directives
      set \$anthropic_api_key "${lib.escapeShellArg "$ANTHROPIC_KEY"}";
      set \$openai_api_key "${lib.escapeShellArg "$OPENAI_KEY"}";
      NGINX_KEYS

      # Critical: only root and aba-proxy can read this file.
      # The aba user must NOT be able to read it.
      chown root:aba-proxy "${apiKeysConf}"
      chmod 0640 "${apiKeysConf}"
    '';
  };

  # --------------------------------------------------------------------------
  # Token manager: keeps a fresh OpenAI OAuth API key on disk
  # --------------------------------------------------------------------------
  #
  # Runs scripts/token-manager.sh as a long-running service.
  # Every 7 minutes it refreshes the OAuth token and writes a fresh API key
  # to /run/aba-proxy/openai-token. The nginx OpenAI location reads this file
  # for its Authorization header instead of using a static key.
  #
  systemd.services.token-manager = {
    description = "OpenAI OAuth token manager -- refresh and exchange loop";
    wantedBy = [ "multi-user.target" ];
    before = [ "nginx.service" ];
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    serviceConfig = {
      Type = "simple";
      Restart = "always";
      RestartSec = 30;
      User = "root";
      Group = "root";
      # token-manager.sh is deployed alongside the NixOS config
      ExecStart = "${pkgs.bash}/bin/bash /var/lib/aba/token-manager.sh";
      # Hardening
      ProtectHome = true;
      NoNewPrivileges = true;
      PrivateTmp = true;
    };
    path = [ pkgs.curl pkgs.jq pkgs.coreutils config.services.nginx.package ];
  };

  # --------------------------------------------------------------------------
  # nginx reverse proxy: API key injection
  # --------------------------------------------------------------------------
  #
  # Security model:
  #   - Listens ONLY on 127.0.0.1:8080 (not on any public interface)
  #   - ABA sends requests to localhost:8080/{anthropic,openai}/...
  #   - nginx injects the correct auth header per provider
  #   - ABA never sees the key -- it's added server-side
  #   - Access logs do NOT include auth headers (custom log format)
  #   - The aba user cannot read the key config file (ownership: root:aba-proxy)
  #
  services.nginx = {
    enable = true;

    # Run nginx workers as aba-proxy so they can read api-keys.inc
    user = "aba-proxy";
    group = "aba-proxy";

    # Disable the default "Welcome to nginx" page
    statusPage = false;

    # Custom log format that explicitly excludes auth headers.
    # Even if someone adds $http_authorization to a log format later,
    # proxy_hide_header prevents it from appearing in responses.
    commonHttpConfig = ''
      log_format api_proxy '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent" '
                           'rt=$request_time';
    '';

    virtualHosts."api-proxy" = {
      listen = [
        {
          addr = "127.0.0.1";
          port = 8080;
        }
      ];

      # Do not serve anything at the root -- only proxy paths are valid
      locations."/" = {
        return = "404";
      };

      # Include the generated key config (contains $anthropic_api_key, $openai_api_key)
      extraConfig = ''
        include ${apiKeysConf};
        access_log /var/log/nginx/api-proxy.log api_proxy;
      '';

      # ---------------------------------------------------------------
      # Anthropic API proxy
      # ---------------------------------------------------------------
      # ABA calls: POST http://127.0.0.1:8080/anthropic/v1/messages
      # nginx forwards to: POST https://api.anthropic.com/v1/messages
      # with x-api-key header injected
      locations."/anthropic/" = {
        proxyPass = "https://api.anthropic.com/";
        extraConfig = ''
          # Inject the Anthropic API key (read from the keys config)
          proxy_set_header x-api-key $anthropic_api_key;

          # Strip any auth headers ABA might send (defense in depth)
          proxy_set_header Authorization "";

          # Required for HTTPS upstream with SNI
          proxy_ssl_server_name on;

          # Pass through content-type and accept headers from ABA
          proxy_set_header Content-Type $http_content_type;
          proxy_set_header Accept $http_accept;
          proxy_set_header anthropic-version $http_anthropic_version;

          # Do not pass the Host header -- use the upstream's hostname
          proxy_set_header Host api.anthropic.com;

          # Timeouts: LLM calls can take a while (streaming, long context)
          proxy_read_timeout 300s;
          proxy_connect_timeout 10s;
          proxy_send_timeout 30s;

          # Buffer settings for potentially large responses
          proxy_buffering off;  # Support streaming responses
          proxy_request_buffering off;

          # Hide auth-related headers from responses (defense in depth)
          proxy_hide_header x-api-key;
        '';
      };

      # ---------------------------------------------------------------
      # OpenAI API proxy
      # ---------------------------------------------------------------
      # ABA calls: POST http://127.0.0.1:8080/openai/v1/chat/completions
      # nginx forwards to: POST https://api.openai.com/v1/chat/completions
      # with Authorization: Bearer header injected.
      #
      # The token is read from /run/aba-proxy/openai-key.inc, which is
      # an nginx snippet setting $openai_oauth_key. The token-manager
      # systemd service rewrites this file every 7 minutes and sends
      # SIGHUP to nginx so it picks up the new value without downtime.
      # Falls back to $openai_api_key from api-keys.inc if the OAuth
      # key file does not exist.
      locations."/openai/" = {
        proxyPass = "https://api.openai.com/";
        extraConfig = ''
          # Include the OAuth-derived key if the token-manager has written it.
          include /run/aba-proxy/openai-key.inc;

          # Inject the OpenAI Bearer token (prefer OAuth key, fall back to SOPS key)
          proxy_set_header Authorization "Bearer $openai_oauth_key";

          # Required for HTTPS upstream with SNI
          proxy_ssl_server_name on;

          # Pass through content-type and accept headers from ABA
          proxy_set_header Content-Type $http_content_type;
          proxy_set_header Accept $http_accept;

          # Do not pass the Host header -- use the upstream's hostname
          proxy_set_header Host api.openai.com;

          # Timeouts: LLM calls can take a while
          proxy_read_timeout 300s;
          proxy_connect_timeout 10s;
          proxy_send_timeout 30s;

          # Buffer settings for potentially large responses
          proxy_buffering off;  # Support streaming responses
          proxy_request_buffering off;

          # Hide auth-related headers from responses (defense in depth)
          proxy_hide_header Authorization;
        '';
      };

      # ---------------------------------------------------------------
      # Health check endpoint
      # ---------------------------------------------------------------
      # ABA or monitoring can hit this to verify the proxy is running.
      # Returns 200 without touching any upstream API.
      locations."= /health" = {
        return = "200 'ok'";
        extraConfig = ''
          add_header Content-Type text/plain;
        '';
      };
    };
  };

  # Ensure nginx logs directory exists and is writable by the proxy user
  systemd.services.nginx.serviceConfig = {
    # Additional hardening for the nginx service
    ProtectHome = true;             # Cannot access /home (where aba lives)
    ProtectSystem = "strict";       # Read-only filesystem except explicit paths
    ReadWritePaths = [
      "/var/log/nginx"
      "/run/nginx"
      "/run/aba-proxy"  # Token manager writes openai-key.inc here; nginx reads it
    ];
    NoNewPrivileges = true;         # Cannot gain additional privileges
    PrivateTmp = true;              # Isolated /tmp
  };

  # --------------------------------------------------------------------------
  # Automatic security updates
  # --------------------------------------------------------------------------
  system.autoUpgrade = {
    enable = true;
    allowReboot = false;  # Don't auto-reboot -- ABA might be mid-loop
    dates = "04:00";      # Check daily at 4 AM UTC
  };

  # --------------------------------------------------------------------------
  # Swap -- small VPS might need it for Rust compilation
  # --------------------------------------------------------------------------
  swapDevices = [
    {
      device = "/swapfile";
      size = 2048;  # 2 GB swap
    }
  ];

  # --------------------------------------------------------------------------
  # Timezone and locale
  # --------------------------------------------------------------------------
  time.timeZone = "UTC";
  i18n.defaultLocale = "en_US.UTF-8";
}
