#!/usr/bin/env bash
# token-manager.sh -- Keeps a fresh OpenAI API key on disk for the nginx proxy.
#
# Runs as a systemd service on the NixOS VPS. Every 7 minutes it:
#   1. Reads the SOPS-decrypted refresh token from /var/lib/aba/oauth-refresh-token
#   2. Refreshes the token to get a new id_token (and possibly a rotated refresh_token)
#   3. Exchanges the id_token for an OpenAI API key
#   4. Writes the API key as an nginx include snippet to /run/aba-proxy/openai-key.inc
#   5. Sends SIGHUP to nginx so it picks up the new key without downtime
#
# nginx includes /run/aba-proxy/openai-key.inc which sets $openai_oauth_key.
# File permissions: root:aba-proxy 0640
#
# Required env (set by systemd unit or defaults):
#   CLIENT_ID          -- OAuth client ID (default: app_EMoamEEZ73f0CkXaXp7hrann)
#   TOKEN_URL          -- OAuth token endpoint
#   REFRESH_TOKEN_FILE -- Path to the SOPS-decrypted refresh token
#   OUTPUT_DIR         -- Directory for the nginx include file

set -euo pipefail

CLIENT_ID="${CLIENT_ID:-app_EMoamEEZ73f0CkXaXp7hrann}"
TOKEN_URL="${TOKEN_URL:-https://auth.openai.com/oauth/token}"
REFRESH_TOKEN_FILE="${REFRESH_TOKEN_FILE:-/var/lib/aba/oauth-refresh-token}"
OUTPUT_DIR="${OUTPUT_DIR:-/run/aba-proxy}"
OUTPUT_FILE="${OUTPUT_DIR}/openai-key.inc"
RAW_TOKEN_FILE="${OUTPUT_DIR}/openai-token"
REFRESH_INTERVAL="${REFRESH_INTERVAL:-420}"  # 7 minutes in seconds

log() {
    echo "[token-manager] $(date -u '+%Y-%m-%dT%H:%M:%SZ') $*"
}

write_nginx_include() {
    local api_key="$1"
    # Write an nginx snippet that sets the variable used by the proxy location.
    cat > "$OUTPUT_FILE" <<NGINX_INC
# AUTO-GENERATED by token-manager.sh -- do not edit manually.
# Refreshed every ${REFRESH_INTERVAL}s via OAuth token exchange.
set \$openai_oauth_key "${api_key}";
NGINX_INC
    chown root:aba-proxy "$OUTPUT_FILE"
    chmod 0640 "$OUTPUT_FILE"

    # Also write the raw token for non-nginx consumers.
    echo -n "$api_key" > "$RAW_TOKEN_FILE"
    chown root:aba-proxy "$RAW_TOKEN_FILE"
    chmod 0640 "$RAW_TOKEN_FILE"
}

refresh_and_exchange() {
    if [ ! -f "$REFRESH_TOKEN_FILE" ]; then
        log "ERROR: Refresh token file not found: $REFRESH_TOKEN_FILE"
        return 1
    fi

    local refresh_token
    refresh_token="$(cat "$REFRESH_TOKEN_FILE")"

    if [ -z "$refresh_token" ]; then
        log "ERROR: Refresh token file is empty"
        return 1
    fi

    # Step 1: Refresh the token to get a new id_token.
    log "Refreshing token..."
    local refresh_response
    refresh_response="$(curl -s -X POST "$TOKEN_URL" \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        -d "grant_type=refresh_token" \
        -d "client_id=${CLIENT_ID}" \
        -d "refresh_token=${refresh_token}")"

    local id_token
    id_token="$(echo "$refresh_response" | jq -r '.id_token // empty')"
    if [ -z "$id_token" ]; then
        local err
        err="$(echo "$refresh_response" | jq -r '.error // "unknown"')"
        log "ERROR: Token refresh failed: $err"
        return 1
    fi

    # If the server rotated the refresh token, persist the new one.
    local new_refresh_token
    new_refresh_token="$(echo "$refresh_response" | jq -r '.refresh_token // empty')"
    if [ -n "$new_refresh_token" ] && [ "$new_refresh_token" != "$refresh_token" ]; then
        log "Refresh token rotated, updating on disk."
        echo -n "$new_refresh_token" > "$REFRESH_TOKEN_FILE"
        chown root:root "$REFRESH_TOKEN_FILE"
        chmod 0400 "$REFRESH_TOKEN_FILE"
    fi

    # Step 2: Exchange the id_token for an OpenAI API key.
    log "Exchanging id_token for API key..."
    local exchange_response
    exchange_response="$(curl -s -X POST "$TOKEN_URL" \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        -d "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
        -d "client_id=${CLIENT_ID}" \
        -d "requested_token=openai-api-key" \
        -d "subject_token=${id_token}" \
        -d "subject_token_type=urn:ietf:params:oauth:token-type:id_token")"

    local api_key
    api_key="$(echo "$exchange_response" | jq -r '.access_token // empty')"
    if [ -z "$api_key" ]; then
        local err
        err="$(echo "$exchange_response" | jq -r '.error // "unknown"')"
        log "ERROR: Token exchange failed: $err"
        return 1
    fi

    # Step 3: Write the nginx include and raw token file.
    write_nginx_include "$api_key"
    log "Wrote fresh API key to $OUTPUT_FILE"

    # Step 4: Signal nginx to reload its config and pick up the new key.
    if command -v nginx >/dev/null 2>&1 && nginx -t 2>/dev/null; then
        nginx -s reload 2>/dev/null || true
        log "Sent reload signal to nginx."
    fi
}

# --- Main loop ---

log "Starting token manager (interval: ${REFRESH_INTERVAL}s)"

# Ensure the output directory exists (should be created by tmpfiles, but be safe).
mkdir -p "$OUTPUT_DIR"
chown root:aba-proxy "$OUTPUT_DIR"
chmod 0750 "$OUTPUT_DIR"

# Write a placeholder so nginx can start even before the first refresh succeeds.
if [ ! -f "$OUTPUT_FILE" ]; then
    write_nginx_include "PLACEHOLDER_AWAITING_FIRST_REFRESH"
    log "Wrote placeholder nginx include (first refresh pending)."
fi

# Run once immediately at startup, then loop.
while true; do
    if ! refresh_and_exchange; then
        log "WARN: Refresh cycle failed, will retry in ${REFRESH_INTERVAL}s"
    fi
    sleep "$REFRESH_INTERVAL"
done
